[tool.poetry]
name = "ythesis"
version = "0.1.2"
description = "provides thesis entities"
readme = "Readme.markdown"
keywords = ["thesis"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
authors = ["yassu <yasu0320.dev@gmail.com>"]
repository = "https://gitlab.com/yassu/ythesis"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
flake8-quotes = "^3.2.0"
invoke = "^1.4.1"
ipython = "^7.18.1"
isort = "^5.5.2"
mypy = "^0.782"
pudb = "^2019.2"
py-term = "^0.6"
pytest = "^6.0.2"
pytest-cov = "^2.10.1"
yapf = "^0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
