[tool.poetry]
name = "MCDRTelegram"
version = "0.3.0"
description = ""
authors = ["Yi-Jyun Pan <pan93412@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^2.11.2"
uvloop = "^0.14.0"
ujson = "^4.0.2"

[tool.poetry.dev-dependencies]
mypy = "^0.800"
yapf = "^0.30.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
