#  local xt_config.yaml file for XT Demo

general:
    advanced-mode: false                # run both basic and full xt_demo in basic mode
    workspace: rf356-v3 
    experiment: "xt-demo"              # default name of experiment associated with each run

    # metrics
    primary-metric: "test-acc"         # name of metric to optimize in roll-ups, hyperparameter search, and early stopping
    maximize-metric: true              # how primary metric is aggregated for hp search, hp explorer, early stopping 
    step-name: "epoch"                 # name of a single step

code:
    code-omit: [".git", "__pycache__", "logs", "data"]      # directories and files to omit when capturing before/after files

store: sandbox_v3

data:
    # note: XT_DATA_DIR on cloud, pool, or local will always point to .../data/mnist
    data-share-path: "mnist"               # path to data in data share 
    data-local: "$scriptdir/../data"       # local directory of data for app
    data-action: "mount"                   # data action at start of run: none, download, mount
    data-writable : false

model:
    # note: XT_MODEL_DIR on cloud, pool, or local will always point to .../models/miniMnist
    model-local: "$scriptdir/../models"    # local directory of model for app
    model-share-path: "miniMnist"          # path to model in model share
    model-action: "mount"                  # model action at start of run: none, download, mount
    model-writable: true

hyperparameter-search:
    fn-generated-config: "runset.yaml"     # name of runset file generated by dynamic hyperparameter search

hyperparameter-explorer:
    steps-name: "epochs"                   # name of metric that represents total # of steps taken 
    log-interval-name: "log-interval"      # name of hyperparameter that specifies # of steps between metric reports

run-reports:
    columns: ["run", "job", 
        "created:$to", "experiment", "box", "queued", "target", "runs",  "search", "search_style=style", "status", 
        "tags.priority", "tags.description", "tags.top5", "tags.good_run",
        "hparams.lr", "hparams.momentum", "hparams.optimizer",
        "metrics.*",
        "duration", 
        ]

job-reports:
    columns: ["job", "created", "started", "workspace", "experiment", "target", "nodes", "runs", "repeat", "tags.description", "tags.urgent", "tags.sad=SADD", "tags.funny", "low_pri", 
        "vm_size", "azure_image", "service", "vc", "cluster", "queue", "service_type", "search", "search_style",
        "job_status:$bz", "running_nodes:$bz", "running_runs:$bz", "error_runs:$bz", "completed_runs:$bz"]

