[tool.poetry]
name = "django-split-input"
version = "0.2.2"
description = "A widget to have a django text input split into multiple HTML inputs."
authors = ["Julian Leucker <leuckerj@gmail.com>"]
readme = "README.md"
repository = "https://edugit.org/AlekSIS/libs/django-split-input"
keywords = ["django", "widget"]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django :: 3.1",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Typing :: Typed",
]


[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
