[tool.poetry]
name = "mongoengine-arrow"
version = "0.1.2"
description = "Arrow datetime support for MongoEngine"
authors = ["Niko JÃ¤rvinen <nbjarvinen@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/b10011/arrow-mongoengine"
repository = "https://github.com/b10011/arrow-mongoengine"
documentation = "https://github.com/b10011/arrow-mongoengine"
keywords = ["arrow", "mongoengine", "database"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries",
  "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.6"
mongoengine = "^0.22.1"
arrow = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
