[tool.poetry]
authors = ["Nom Nom Data Inc <info@nomnomdata.com>"]
description = "Package containing tooling for developing nominode engines"
license = "LGPL-3.0-only"
name = "nomnomdata-cli"
packages = [
  {include = "nomnomdata"},
]
readme = "README.md"
repository = "https://gitlab.com/nomnomdata/tools/nomnomdata-engine"
version = "0.1.10"

[tool.poetry.plugins."console_scripts"]
nnd = "nomnomdata.cli.cli:main"

[tool.poetry.dependencies]
click = "^7.1.2"
coloredlogs = "^14.0"
dunamai = "^1.1.0"
packaging = "^20.4"
python = "^3.7"
requests = "^2.23.0"
rich = "^9.0.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.2"
isort = "^5.7.0"
pre-commit = "^2.10.0"
pytest = "^6.0.1"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.black]
include = '\.pyi?$'
line-length = 90
target-version = ['py37', 'py38']

[tool.isort]
default_section = 'THIRDPARTY'
ensure_newline_before_comments = true
force_grid_wrap = 0
force_to_top = ['nomnomdata']
include_trailing_comma = true
known_first_party = ['nomnomdata', 'nominode', 'nomcom', 'engines_common', 'nomitall']
line_length = 90
multi_line_output = 3
use_parentheses = true

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = 90
