[tool.poetry]
name = "safeops-cli"
version = "0.1.0"
description = ""
authors = ["Andres moreno <amoreno@opsline.com>"]
packages = [{include = "cli.py"}]

[tool.poetry.scripts]
safeops="cli:process"

[tool.poetry.dependencies]
python = "^3.8.6"
click = "^7.1.2"
funcy = "^1.15"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
