[tool.poetry]
name = "terramare"
version = "0.4.2"
description = "Automatically deserialize complex objects from simple Python types"
authors = ["Tom W <796618-tomwatson1024@users.noreply.gitlab.com>"]
readme = "README.md"
repository = "https://gitlab.com/tomwatson1024/terramare"
documentation = "https://tomwatson1024.gitlab.io/terramare"
license = "MIT"
include = ["CHANGELOG.md", "docs/emoji.png"]

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^19.1"
dataclasses = { version = "^0.7", python = "~3.6" }
python-dateutil = "^2.8.1"
result = "~0.5"
typing-extensions = "^3.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.3"
flake8 = "^3.8.4"
flake8-print = "^3.1.4"
mypy = "^0.782"
pydocstyle = "^5.1.1"
pylint = "^2.6"
pytest = "^6.1.1"
"ruamel.yaml" = "^0.16.5"
sphinx = "^3.2.1"
sphinx-typlog-theme = "^0.8.0"
toml = "^0.10.1"
tox = "^3.20"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
