[tool.poetry]
name = "gsimplify"
version = "0.0.16"
description = ""
authors = ["echapman2022 <ethan.chapman0@outlook.com>", "Max Fan <root@max.fan>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/ChoateProgrammingUnion/simplify"

[tool.poetry.dependencies]
python = ">=3.6"
google-api-python-client = "^1.12.5"
google-auth-httplib2 = "^0.0.4"
google-auth-oauthlib = "^0.4.2"
pydantic = "^1.7.2"
Jinja2 = "^2.11.2"
gitpython = "^3.1.11"
tqdm = "^4.53.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
