[tool.poetry]
name = "samtecdeviceshare"
version = "2.6.2"
description = "Handles a variety of common routines for SDC-based applications"
readme = "README.md"
authors = ["Adam Page <adam.page@samtec.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
uvicorn = "^0.13.3"
pydantic = "^1.7.3"
pyhumps = "^1.6.1"
python-networkmanager = { version = "*",  platform = "linux"}
dbus-python = { version = "*",  platform = "linux"}
httpx = "^0.16.1"
PyYAML = "^5.4.1"
aiofiles = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pylint = "^2.6.0"
twine = "^3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
