[tool.poetry]
name = "mongoengine-arrow"
version = "0.1.1"
description = "Arrow datetime support for MongoEngine"
authors = ["Niko JÃ¤rvinen <nbjarvinen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
mongoengine = "^0.22.1"
arrow = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
